ral-facilities/inventory-management-system

cypress/e2e/catalogue/catalogueItems.cy.ts
cypress/e2e/manufacturer/manufacturer.cy.ts
src/catalogue/items/__snapshots__/catalogueItemsTable.component.test.tsx.snap
src/catalogue/items/catalogueItemsTable.component.test.tsx
src/catalogue/items/catalogueItemsTable.component.tsx
src/manufacturer/__snapshots__/manufacturer.component.test.tsx.snap
src/manufacturer/manufacturer.component.test.tsx
src/manufacturer/manufacturer.component.tsx

Add Clear filters button to the catalogue items and manufacturer table
closes #156

Clear filters and Change range slider to range input fields #156

---

cypress/e2e/system.cy.ts
src/api/systems.test.tsx
src/api/systems.tsx
src/app.types.tsx
src/catalogue/category/catalogueCategoryDirectoryDialog.component.tsx
src/mocks/Systems.json
src/systems/systemDirectoryDialog.component.test.tsx
src/systems/systemDirectoryDialog.component.tsx
src/systems/systems.component.test.tsx
src/systems/systems.component.tsx
src/systems/systemsTableView.component.test.tsx
src/systems/systemsTableView.component.tsx

Adds the ability to copy one or more systems to another system.
Closes #136

Copy systems #136

---

src/catalogue/category/catalogueCategoryDialog.component.tsx

See issue/comment in code.
Closes #175

Fix catalogue category properties not being reset #175

---

src/catalogue/category/catalogueCategoryDialog.component.tsx
src/manufacturer/manufacturerDialog.component.tsx

Refactored catalogue categories to use grid, updated edit function, and refactored error states in manufacturer dialog
closes #127

Refactor catalogue category #127

---

cypress/e2e/system.cy.ts
src/api/catalogueCategory.test.tsx
src/api/catalogueCategory.tsx
src/api/systems.test.tsx
src/api/systems.tsx
src/app.types.tsx
src/catalogue/category/catalogueCategoryDirectoryDialog.component.tsx
src/catalogue/items/catalogueItemsTable.component.tsx
src/manufacturer/manufacturer.component.tsx
src/systems/deleteSystemDialog.component.test.tsx
src/systems/deleteSystemDialog.component.tsx
src/systems/systemDetails.component.test.tsx
src/systems/systemDetails.component.tsx
src/systems/systemDialog.component.test.tsx
src/systems/systemDialog.component.tsx
src/systems/systemDirectoryDialog.component.tsx
src/systems/systems.component.test.tsx
src/systems/systems.component.tsx
src/utils.test.tsx
src/utils.tsx

- Adds a menu to each system/subsystem with edit, save as and delete (which has been removed from the landing page)
- Adds save as dialog
Closes #137

Save as system #137

---

cypress/e2e/system.cy.ts
src/catalogue/items/__snapshots__/catalogueItemsTable.component.test.tsx.snap
src/catalogue/items/catalogueItemsTable.component.tsx
src/manufacturer/__snapshots__/manufacturer.component.test.tsx.snap
src/manufacturer/manufacturer.component.tsx
src/systems/systemDetails.component.tsx
src/systems/systemDirectoryDialog.component.test.tsx
src/systems/systemDirectoryDialog.component.tsx
src/systems/systems.component.test.tsx
src/systems/systems.component.tsx
src/utils.tsx
src/view/viewTabs.component.tsx

- Displays subsystems using MRT
- Adds scroll bar for systems
- Adds pagination for systems
- Changes the way pages obtain their height - this means all full page tables had to be adjusted
- Addresses https://github.com/ral-facilities/inventory-management-system/pull/205#pullrequestreview-1810764751
connect to {issue number}

Systems pagination #125

---

cypress/e2e/system.cy.ts
src/systems/systemDetails.component.test.tsx
src/systems/systemDetails.component.tsx
src/systems/systems.component.tsx

Adds system not found message when a system isn't found.
Also adjusts table height when the breadcrumbs are loading, so the pagination component remains in the same place when the loading finishes.
Closes #233

System not found message

---

cypress/e2e/catalogue/catalogueItems.cy.ts
src/api/manufacturer.test.tsx
src/catalogue/items/CatalogueItemsDetailsPanel.component.tsx
src/catalogue/items/__snapshots__/CatalogueItemsDetailsPanel.component.test.tsx.snap
src/catalogue/items/__snapshots__/catalogueItemsTable.component.test.tsx.snap
src/catalogue/items/catalogueItemsLandingPage.component.tsx
src/manufacturer/__snapshots__/manufacturer.component.test.tsx.snap
src/manufacturer/manufacturerLandingPage.component.test.tsx
src/manufacturer/manufacturerLandingPage.component.tsx
src/mocks/manufacturer.json

Tweaked landing pages and details panel in catalogue items for the manufacturer address.
Changed styling on manufacturer page so looks as it should in production
closes #218

minor tweaks to manufacturer #218

---

src/catalogue/items/catalogueItemsLandingPage.component.tsx
src/items/ItemsDetailsPanel.component.test.tsx
src/items/ItemsDetailsPanel.component.tsx
src/items/__snapshots__/ItemsDetailsPanel.component.test.tsx.snap
src/items/__snapshots__/itemsTable.component.test.tsx.snap
src/items/items.component.tsx
src/items/itemsTable.component.test.tsx
src/items/itemsTable.component.tsx
src/manufacturer/manufacturerLandingPage.component.tsx
src/setupTests.tsx

Dense table view for moving items into systems 
closes #225

View items table dense #225

---

cypress/e2e/items.cy.ts
cypress/e2e/manufacturer/manufacturer.cy.ts
src/api/Item.test.tsx
src/api/item.tsx
src/catalogue/items/CatalogueItemsDetailsPanel.component.test.tsx
src/catalogue/items/CatalogueItemsDetailsPanel.component.tsx
src/catalogue/items/__snapshots__/CatalogueItemsDetailsPanel.component.test.tsx.snap
src/catalogue/items/__snapshots__/catalogueItemsTable.component.test.tsx.snap
src/catalogue/items/catalogueItemsLandingPage.component.test.tsx
src/catalogue/items/catalogueItemsLandingPage.component.tsx
src/catalogue/items/catalogueItemsTable.component.test.tsx
src/items/ItemsDetailsPanel.component.test.tsx
src/items/ItemsDetailsPanel.component.tsx
src/items/__snapshots__/ItemsDetailsPanel.component.test.tsx.snap
src/items/__snapshots__/itemsTable.component.test.tsx.snap
src/items/items.component.tsx
src/items/itemsLandingPage.component.test.tsx
src/items/itemsLandingPage.component.tsx
src/items/itemsTable.component.test.tsx
src/items/itemsTable.component.tsx
src/manufacturer/__snapshots__/manufacturer.component.test.tsx.snap
src/manufacturer/manufacturer.component.test.tsx
src/manufacturer/manufacturer.component.tsx
src/manufacturer/manufacturerLandingPage.component.test.tsx
src/manufacturer/manufacturerLandingPage.component.tsx
src/mocks/CatalogueItems.json
src/mocks/Items.json
src/mocks/handlers.ts
src/view/viewTabs.component.tsx

Landing page for item
use useParams instead of useLocation for the landing pages 
Change it to use Telephone number everywhere instead of Telephone
Allow the Telephone number to be None as it is an optional field
closes #229

Landing page items #229

---

cypress/e2e/catalogue/catalogueItems.cy.ts
cypress/e2e/items.cy.ts
cypress/e2e/manufacturer/manufacturer.cy.ts
src/catalogue/catalogue.component.tsx
src/catalogue/items/catalogueItemsLandingPage.component.test.tsx
src/catalogue/items/catalogueItemsLandingPage.component.tsx
src/items/items.component.test.tsx
src/items/items.component.tsx
src/items/itemsLandingPage.component.test.tsx
src/items/itemsLandingPage.component.tsx
src/manufacturer/__snapshots__/manufacturer.component.test.tsx.snap
src/manufacturer/manufacturer.component.test.tsx
src/manufacturer/manufacturer.component.tsx
src/manufacturer/manufacturerLandingPage.component.test.tsx
src/manufacturer/manufacturerLandingPage.component.tsx
src/systems/systems.component.tsx
src/view/__snapshots__/breadcrumbs.component.test.tsx.snap
src/view/breadcrumbs.component.tsx

Adding the breadcrumbs to the landing pages and items and manufacturers 
closes #232 , closes #116

Breadcrumbs landingpage item #232

---

cypress/e2e/catalogue/catalogueCategory.cy.ts
cypress/e2e/catalogue/catalogueItems.cy.ts
cypress/e2e/manufacturer/manufacturer.cy.ts
cypress/support/commands.ts

Done as there were only a few and will need to be done for MSW v2 at some point anyway.
Closes #111

Remove deprecated uses of body from MSW

---

src/catalogue/items/catalogueItemsDialog.component.tsx
src/manufacturer/manufacturer.component.tsx
src/manufacturer/manufacturerDialog.component.test.tsx
src/manufacturer/manufacturerDialog.component.tsx
src/manufacturer/manufacturerLandingPage.component.tsx

manufacturer-dialog-bug-fix #253

---

Dockerfile
Dockerfile.prod

For some reason renovate didn't pick this up despite having the same config as datagateway. We already upgraded the types and use v20 for development.

Update dockerfile node base image to 20.11-alpine3.19

---

cypress/e2e/catalogue/catalogueItems.cy.ts
cypress/e2e/items.cy.ts
src/catalogue/items/__snapshots__/catalogueItemsDialog.component.test.tsx.snap
src/catalogue/items/catalogueItemsDialog.component.test.tsx
src/catalogue/items/catalogueItemsDialog.component.tsx
src/items/itemDialog.component.test.tsx
src/items/itemDialog.component.tsx
src/mocks/CatalogueCategory.json
src/mocks/CatalogueItems.json
src/mocks/Items.json

When the catalogue item property has allowed list of values it renders a select component with the options  
closes #292

allowed value list in the dialogs #292

---

src/catalogue/category/deleteCatalogueCategoryDialog.component.test.tsx
src/catalogue/category/deleteCatalogueCategoryDialog.component.tsx
src/catalogue/items/catalogueItemsDialog.component.test.tsx
src/catalogue/items/deleteCatalogueItemDialog.component.tsx
src/items/__snapshots__/deleteItemDialog.component.test.tsx.snap
src/items/deleteItemDialog.component.tsx
src/manufacturer/deleteManufacturerDialog.component.tsx
src/systems/deleteSystemDialog.component.tsx

Add warning icon and permanent to delete dialogues #252

---

src/catalogue/catalogue.component.test.tsx
src/catalogue/category/catalogueCardView.component.test.tsx
src/catalogue/category/catalogueCategoryDirectoryDialog.component.test.tsx
src/catalogue/items/catalogueItemsTable.component.tsx
src/items/itemsTable.component.tsx
src/manufacturer/manufacturer.component.tsx
src/manufacturer/manufacturerDialog.component.tsx
src/view/viewTabs.component.test.tsx
src/view/viewTabs.component.tsx

Enter a description of the changes here
closes #296

fix errors found in unit test on the CI

---

cypress/e2e/catalogue/catalogueItems.cy.ts
src/catalogue/items/__snapshots__/catalogueItemsDialog.component.test.tsx.snap
src/catalogue/items/__snapshots__/catalogueItemsTable.component.test.tsx.snap
src/catalogue/items/catalogueItemsDialog.component.test.tsx
src/catalogue/items/catalogueItemsDialog.component.tsx

Use stepper for catalogue items 
closes #297

use stepper for catalogue items dialog #297

---

cypress/e2e/catalogue/catalogueCategory.cy.ts
src/api/units.test.tsx
src/api/units.tsx
src/app.types.tsx
src/catalogue/category/__snapshots__/cataloguePropertiesForm.component.test.tsx.snap
src/catalogue/category/catalogueCategoryDialog.component.test.tsx
src/catalogue/category/cataloguePropertiesForm.component.test.tsx
src/catalogue/category/cataloguePropertiesForm.component.tsx
src/mocks/handlers.ts
src/mocks/units.json

Adds unit autocomplete to the catalogue category dialog 
closes #266

units #266

---

cypress/e2e/with_api/manufacturer.cy.ts
cypress/support/commands.ts

Manufacturer system integration tests #337

---

cypress/e2e/with_api/app.cy.ts
cypress/e2e/with_api/catalogueCategory/catalogueCategory.cy.ts
cypress/e2e/with_api/catalogueCategory/functions.ts
cypress/e2e/with_api/catalogueItem/catelogueItem.cy.ts
cypress/e2e/with_api/catalogueItem/functions.ts
cypress/e2e/with_api/manufacturer/functions.ts
cypress/e2e/with_api/manufacturer/manufacturer.cy.ts
cypress/support/commands.ts
package.json
src/catalogue/items/catalogueItemsTable.component.tsx

catalogue item systems tests 
recognizing e2e with api 
add aria-label to table row 
closes #334

Catalogue item system integration tests #334

---

cypress/e2e/with_api/systems/functions.ts
cypress/e2e/with_api/systems/systems.cy.ts

systems system integration tests #336

---

src/catalogue/category/catalogueCategoryTableView.component.tsx
src/catalogue/items/__snapshots__/catalogueItemsTable.component.test.tsx.snap
src/catalogue/items/catalogueItemsTable.component.tsx
src/items/__snapshots__/itemsTable.component.test.tsx.snap
src/items/itemsTable.component.tsx
src/manufacturer/__snapshots__/manufacturer.component.test.tsx.snap
src/manufacturer/manufacturer.component.tsx

Added Ids to columns that use `accessorFn` across all tables (catalogue category/items, manufacturers)
closes #250

Id column headers #250

---

src/homePage/homePage.component.test.tsx
src/homePage/homePage.component.tsx

homepage buttons darkMode #357

---

.github/workflows/ci-build.yml
cypress.config.ts

Enter a description of the changes here
connect to {issue number}

Add cors vars to env vars for e2e with api tests

---

craco.config.js
cypress/e2e/with_api/app.cy.ts
cypress/e2e/with_api/catalogueCategory/catalogueCategory.cy.ts
cypress/e2e/with_api/catalogueCategory/functions.ts
cypress/e2e/with_api/catalogueItem/catelogueItem.cy.ts
cypress/e2e/with_api/catalogueItem/functions.ts
cypress/e2e/with_api/items/functions.ts
cypress/e2e/with_api/items/items.cy.ts
cypress/e2e/with_api/manufacturer/functions.ts
cypress/e2e/with_api/manufacturer/manufacturer.cy.ts
cypress/e2e/with_api/systems/functions.ts
cypress/e2e/with_api/systems/systems.cy.ts
cypress/support/commands.ts
src/catalogue/category/catalogueCategoryDirectoryDialog.component.test.tsx
src/catalogue/category/catalogueCategoryDirectoryDialog.component.tsx
src/catalogue/items/catalogueItemDirectoryDialog.component.tsx
src/systems/systemDirectoryDialog.component.tsx
src/systems/systemItemsDialog.component.tsx

- Only clearing the relevant collections
- Skip some checks for setup  
- Fix the disabled button logic for systems (directory Dialog) and catalogue category (directory Dialog) 
connect to {issue number}

Improve e2e test

---

src/handleTransferState.test.ts
src/handleTransferState.ts

Allow the transfer state success and warning to be visible in scigateway
closes #355

Makes all transfer state toast visible #355

---

src/manufacturer/manufacturerLandingPage.component.tsx

add start icon for edit and print buttons on the landing page in manufacturers 
closes #401

Add start icons to manufacturer landing page #401

---

src/catalogue/items/catalogueItemsDialog.component.tsx
src/items/itemDialog.component.tsx
src/items/itemsLandingPage.component.test.tsx
src/items/itemsLandingPage.component.tsx

Fixed form error not reseting in cat items. Reset active step in cat items and items dialogs. Fixed issue of systems not showing correctly in item dialog
closes #397

Fix edit cat items and items #397

---

src/items/__snapshots__/itemsTable.component.test.tsx.snap
src/items/itemsTable.component.tsx

fix date font items table #405

---

src/catalogue/items/catalogueItemsDialog.component.test.tsx
src/catalogue/items/catalogueItemsDialog.component.tsx
src/items/itemDialog.component.test.tsx
src/items/itemDialog.component.tsx

allow the user to select None when a allowed list of values is used
closes #391

allow the user to select None when a allowed list of values is used #391

---

src/manufacturer/__snapshots__/manufacturer.component.test.tsx.snap
src/manufacturer/manufacturer.component.tsx

change the manufacturer name filter variant #404)

---

src/items/itemDialog.component.tsx

Fixed bug for add system in items dialog. Same bug as #403

fixed add system bug in items dialog

---

src/systems/systemDetails.component.tsx

system details tweaks #428

---

src/systems/systemItemsTable.component.tsx

 Increase the table container height for system item table #430

---

src/systems/__snapshots__/systemItemsTable.component.test.tsx.snap
src/systems/systemItemsTable.component.tsx

Before:
<br> <br>
After:
closes #433

fix-styling-delivered_date-#433

---

src/manufacturer/__snapshots__/manufacturer.component.test.tsx.snap
src/manufacturer/manufacturer.component.tsx

Enter a description of the changes here
closes #437

change-pagination-for-manufacturers-#437

---

cypress/e2e/with_mock_data/items.cy.ts
src/api/items.test.tsx
src/api/items.tsx
src/app.types.tsx
src/items/__snapshots__/itemsTable.component.test.tsx.snap
src/items/itemDialog.component.test.tsx
src/items/itemDialog.component.tsx

create mulitple items #453

---

src/systems/systemItemsDialog.component.tsx
src/systems/systemItemsTable.component.test.tsx
src/systems/systemItemsTable.component.tsx

Improve error states #480

---

cypress/e2e/with_mock_data/catalogueCategories.cy.ts
src/app.types.tsx
src/catalogue/category/__snapshots__/cataloguePropertiesForm.component.test.tsx.snap
src/catalogue/category/catalogueCategoryDialog.component.test.tsx
src/catalogue/category/catalogueCategoryDialog.component.tsx
src/catalogue/category/cataloguePropertiesForm.component.test.tsx
src/catalogue/category/cataloguePropertiesForm.component.tsx
src/utils.test.tsx
src/utils.tsx

Catalogue item propeties bug #476

---

src/catalogue/items/catalogueItemsDialog.component.tsx
src/utils.test.tsx
src/utils.tsx

Order list of manufacturers used in autocomplete in the catalogue items dialog alphabetically
closes #498

ordered manufacturer list alphabetically #498

---

cypress/e2e/with_api/catalogueCategories/functions.ts
cypress/e2e/with_mock_data/catalogueCategories.cy.ts
src/app.types.tsx
src/catalogue/category/__snapshots__/cataloguePropertiesForm.component.test.tsx.snap
src/catalogue/category/__snapshots__/cataloguePropertyForm.component.test.tsx.snap
src/catalogue/category/catalogueCategoryDialog.component.test.tsx
src/catalogue/category/catalogueCategoryDialog.component.tsx
src/catalogue/category/cataloguePropertiesForm.component.test.tsx
src/catalogue/category/cataloguePropertiesForm.component.tsx
src/catalogue/category/cataloguePropertyForm.component.test.tsx
src/catalogue/category/cataloguePropertyForm.component.tsx

Create properties form #517

---

src/common/preservedTableState.component.test.tsx

fix lint errors from #524 
No errors in the unit test linting

fix lint errors from #524

---

cypress/e2e/with_mock_data/items.cy.ts
src/items/__snapshots__/deleteItemDialog.component.test.tsx.snap
src/items/deleteItemDialog.component.test.tsx
src/items/deleteItemDialog.component.tsx

display serial number in the delete dialog instead of database id 
closes #563

display serial number in delete dialog #563

---

src/catalogue/items/__snapshots__/catalogueItemsDetailsPanel.component.test.tsx.snap
src/catalogue/items/catalogueItemsDetailsPanel.component.tsx
src/catalogue/items/catalogueItemsLandingPage.component.tsx
src/items/__snapshots__/itemsDetailsPanel.component.test.tsx.snap
src/items/itemDialog.component.tsx
src/items/itemsDetailsPanel.component.tsx
src/items/itemsLandingPage.component.tsx

add whiteSpace pre line notes and desc #291

---

src/systems/systemItemsTable.component.tsx

Fix usageStatus system items table using url #579

---

src/items/__snapshots__/itemsTable.component.test.tsx.snap
src/items/itemsTable.component.tsx

Now matches the sizes used on the catalogue items table.
Closes #570

Fix vertical scroll bar on items table #570

---

cypress/e2e/with_mock_data/manufacturers.cy.ts
src/app.types.tsx
src/manufacturer/manufacturerDialog.component.test.tsx
src/manufacturer/manufacturerDialog.component.tsx
src/mocks/handlers.ts

Fixed URL bug caused by removing URL when editing a manufacturer
closes #572

fixed manufacturer url error bug #572

---

src/systems/systems.component.test.tsx
src/systems/systems.component.tsx

See #590. Added a few tests as well.
Closes #590

Use subsystems in total when appropriate #590

---

src/systems/systems.component.tsx

Fix systems page splitting onto new line at wrong size #624

---

cypress/e2e/with_mock_data/catalogueCategories.cy.ts
src/api/api.tsx
src/api/units.test.tsx
src/catalogue/category/catalogueCategoryDialog.component.test.tsx
src/catalogue/category/cataloguePropertiesForm.component.test.tsx
src/catalogue/items/catalogueItemDirectoryDialog.component.tsx
src/catalogue/items/catalogueItemsTable.component.tsx
src/catalogue/items/obsoleteCatalogueItemDialog.component.test.tsx
src/catalogue/items/obsoleteCatalogueItemDialog.component.tsx
src/handleIMS_APIError.ts
src/homePage/__snapshots__/homePage.component.test.tsx.snap
src/homePage/homePage.component.tsx
src/manufacturer/manufacturer.component.tsx
src/parseTokens.test.ts
src/systems/systemDialog.component.test.tsx
src/systems/systemDialog.component.tsx
src/systems/systemItemsTable.component.test.tsx
src/systems/systemItemsTable.component.tsx
src/testUtils.tsx
vite.config.ts

Went through all files running a spell checker extension and any issues I found, including the one in #641.
Closes #641

Fix typos found by spell checker #641

---

src/catalogue/items/__snapshots__/catalogueItemsDetailsPanel.component.test.tsx.snap
src/catalogue/items/catalogueItemsDetailsPanel.component.tsx
src/catalogue/items/catalogueItemsLandingPage.component.tsx
src/items/__snapshots__/itemsDetailsPanel.component.test.tsx.snap
src/items/itemsDetailsPanel.component.tsx
src/items/itemsLandingPage.component.tsx
src/manufacturer/manufacturerLandingPage.component.tsx
src/systems/systemDetails.component.tsx

Fix  word wrapping when a word is extreme long.
- This issue is unlikely to be triggered in most cases expect for URL as user could enter in a long URL  
closes #640

Fix word wrapping on landing Pages and details panels #640

---

src/catalogue/items/__snapshots__/catalogueItemsDetailsPanel.component.test.tsx.snap
src/catalogue/items/catalogueItemsDetailsPanel.component.test.tsx
src/catalogue/items/catalogueItemsDetailsPanel.component.tsx
src/catalogue/items/catalogueItemsLandingPage.component.test.tsx
src/catalogue/items/catalogueItemsLandingPage.component.tsx
src/items/__snapshots__/itemsDetailsPanel.component.test.tsx.snap
src/items/itemsDetailsPanel.component.test.tsx
src/items/itemsDetailsPanel.component.tsx
src/items/itemsLandingPage.component.test.tsx
src/items/itemsLandingPage.component.tsx

Add manufacturer link to the items and catalogue item landing pages and details panels  
closes #645

Add manufacturers link on landing pages #645

---

src/systems/systems.component.tsx

Fix inconsistent button spacing in systems #629

---

src/utils.tsx

Move ref to the typography for overflowTip component so that the correct component is measured

Move ref to the typography for overflowTip component

---

.github/workflows/ci-build.yml

Fix CI after https://github.com/ral-facilities/inventory-management-system-api/pull/289 was merged.

Update CI workflow to use DATABASE__HOST_AND_OPTIONS

---

cypress/e2e/with_api/catalogueCategories/functions.ts
cypress/e2e/with_mock_data/catalogueCategories.cy.ts
cypress/e2e/with_mock_data/homePage.cy.ts
cypress/e2e/with_mock_data/manufacturers.cy.ts
cypress/e2e/with_mock_data/systems.cy.ts
cypress/support/commands.ts
cypress/tsconfig.json
package.json

add cypress directory and yarn to the lint checker 
fix all the cypress linting issues 
closes #658

Enable lint checks on cypress and build #658

---

src/admin/units/deleteUnitsDialog.component.tsx
src/admin/usageStatuses/deleteUsageStatusDialog.component.tsx
src/api/api.tsx
src/api/catalogueCategories.tsx
src/api/catalogueItems.tsx
src/api/items.tsx
src/api/systems.tsx
src/app.types.tsx
src/catalogue/category/catalogueCategoryDialog.component.tsx
src/catalogue/category/deleteCatalogueCategoryDialog.component.tsx
src/catalogue/items/catalogueItemsDialog.component.tsx
src/catalogue/items/deleteCatalogueItemDialog.component.tsx
src/handleIMS_APIError.ts
src/manufacturer/deleteManufacturerDialog.component.tsx
src/manufacturer/manufacturerDialog.component.tsx
src/systems/deleteSystemDialog.component.tsx
src/systems/systemDialog.component.tsx

Rename ErrorParsing to ApiErrorDetail as ErrorParsing is not descriptive enough 
closes #671

Rename ErrorParsing to APIError #671

---

src/catalogue/category/__snapshots__/cataloguePropertiesForm.component.test.tsx.snap
src/catalogue/category/__snapshots__/cataloguePropertyForm.component.test.tsx.snap
src/catalogue/category/cataloguePropertyForm.component.tsx

Increase vertical padding in catalogue property form #678

---

cypress/e2e/with_mock_data/homePage.cy.ts

refactored tests to check url attributes rather than link to url
closes #689

refactored external links test #689

---

.gitignore

See comment on https://github.com/ral-facilities/operationsgateway/pull/377.

Update gitignore to match OperationsGateway

---

.github/workflows/release-build.yml

See #747. We can probably use a caller workflow eventually so we can reuse it, but for now we will just copy and paste them.
Closes #747

Add Docker release-build workflow #747

---

package.json

Create v1.0.0 release version 

Update release version to v1.0.0

---

Dockerfile
Dockerfile.prod

Update node version 20.15.0 to 20.15.1

Update node version 20.15.0 to 20.15.1

---

renovate.json

Allow Renovate patch updates

---

renovate.json

Renovate failed as the base branch v* wasn't found. So will need to be added if we add another release branch later instead.

Fix broken Renovate config

---

renovate.json

Hopefully disables the lockfile maintenance on the main branch. (Found on current Renovate issue)

Disable lockFileMaintenance on main branch

---

src/catalogue/category/catalogueItemPropertiesMigrationDialog.component.tsx
src/catalogue/category/cataloguePropertiesForm.component.tsx
yarn.lock

Fixes yarn dev after https://github.com/ral-facilities/inventory-management-system/commit/716b093bff9e1f0bf1ee51b72013654c09fb645b#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de was merged. Will also need a similar change on main.

Fix yarn dev broken after lockfile maintenance

---

package.json

Update version to v1.0.1

---

renovate.json

- Extend config:best-practices instead of config:base 
- config:base has been updated to config:recommended
- Add a note to lockfile maintenance and assign two reviewers
- Enable alerts for vulnerabilities, assign two reviewers, and add a note
closes #805

Update Renovate Config #805

---

renovate.json

- lockFileMaintenance
- vulnerabilityAlerts

Add reviewers to renovate config

---

src/utils.tsx

Fix table tooltip error

---

package.json

Update version to v1.0.2
- Node upgrade 
- Table tooltip bug fix 

Update version to v1.0.2

---

package.json
yarn.lock

Update dependency axios to v1.7.4 [SECURITY]

---

src/api/api.types.tsx

fix the api types so they exactly match the backend 
closes #936

Fix catalogue item type interfaces #936

---

yarn.lock

Merged two security vulnerabilities, the merge seems to have conflicted in a way that the lockfile needed to be modified on install which is not allowed by the CI so it failed.

Update lockfile after package update broke it

---

src/api/api.types.tsx

Fix item type interfaces
- Use "Required" in the other interfaces/types to simplify logic
closes #963

Fix item type interfaces #963

---

src/api/api.types.tsx
src/api/items.test.tsx
src/api/items.tsx
src/app.types.tsx
src/catalogue/catalogue.component.test.tsx
src/catalogue/catalogue.component.tsx
src/catalogue/items/catalogueItemsTable.component.tsx
src/items/deleteItemDialog.component.test.tsx
src/items/deleteItemDialog.component.tsx
src/items/itemDialog.component.tsx
src/items/itemsDetailsPanel.component.test.tsx
src/items/itemsDetailsPanel.component.tsx
src/items/itemsLandingPage.component.tsx
src/items/itemsTable.component.tsx
src/mocks/Items.json
src/mocks/handlers.ts
src/systems/systemItemsDialog.component.test.tsx
src/systems/systemItemsDialog.component.tsx
src/systems/systemItemsTable.component.test.tsx
src/systems/systemItemsTable.component.tsx
src/testUtils.tsx

- rename item api functions 
- fix item type 
- fix itemJSON
closes #964

Rename item api functions #964

---

cypress/e2e/with_api/items/functions.ts
cypress/e2e/with_mock_data/catalogueCategories.cy.ts
cypress/e2e/with_mock_data/items.cy.ts
src/catalogue/category/catalogueCard.component.test.tsx
src/common/__snapshots__/placeholderImage.component.test.tsx.snap
src/common/placeholderImage.component.test.tsx
src/common/placeholderImage.component.tsx
src/common/tabPanel.component.test.tsx
src/common/tabPanel.component.tsx
src/items/__snapshots__/itemsDetailsPanel.component.test.tsx.snap
src/items/itemsDetailsPanel.component.tsx
src/items/itemsLandingPage.component.test.tsx
src/items/itemsLandingPage.component.tsx
src/utils.tsx
src/view/viewTabs.component.tsx

see #1019
- Add placeholder image
- Add tabs  
- aad image on details panel
closes #1019

Redesign landing page items #1019

---

package.json
src/catalogue/items/catalogueItemsTable.component.tsx

Fix days to rework in catalogue items table #1091

---

src/common/attachments/uploadAttachmentsDialog.component.test.tsx

add a wait in the attachments request 

Fix flaky attachments test

---

cypress/e2e/with_mock_data/catalogueCategories.cy.ts
src/catalogue/category/catalogueCardView.component.test.tsx
src/catalogue/category/catalogueCardView.component.tsx
src/common/cardView/__snapshots__/cardViewFilters.component.test.tsx.snap
src/common/cardView/cardViewFilters.component.test.tsx
src/common/cardView/cardViewFilters.component.tsx

see #713
this is needed for thumbnail pagination and filtering #1099 
close #713

Use MRT for filters and pagination CC Cards #713

---

src/catalogue/category/catalogueCategoryTableView.component.tsx

Add string and datatime filter options 
closes #1125

 Enhance catalogue categories table view filtering #1125

---

src/common/preservedTableState.component.test.tsx
src/common/preservedTableState.component.tsx

See #1148. Merging into main
Links to #1148

Merge filter fix from main #1146

---

package.json

Update version to v1.0.5
Table filtering bug

Update version to v1.0.5

---

src/common/images/imageGallery.component.tsx

The implementation done before was to get it to work with photoswipe. As we are using a custom lightbox this is no needed   

refactor: thumbnail view logic

---

.github/workflows/ci-build.yml

Fix CI issue with libgconf

---

.github/workflows/ci-build.yml

Fix CI issue with libgconf (Main)

---

package.json
src/testUtils.tsx
yarn.lock

Remove uuid package that is no longer used #1235

---

src/api/api.types.tsx
src/app.types.tsx
src/common/attachments/uploadAttachmentsDialog.component.tsx
src/common/images/uploadImagesDialog.component.tsx

Currently the types are just using Meta and Body from Uppy. These should be specific for attachments and images 

Add body and meta types for upload Dialogs

---

src/common/attachments/uploadAttachmentsDialog.component.test.tsx
src/common/attachments/uploadAttachmentsDialog.component.tsx

A temporary PR to investigate issues with the flaky test in `UploadAttachmentsDialog.component.tsx`. I have not been able to recreate the same errors in my VM, so I'm investigating on the Github CI.

Investigate flaky ci tests for upload attachments dialog

---

renovate.json

Update my username in the renovate config 

Update username on renovate config

---

.github/workflows/ci-build.yml

update the env vars for ims api in the ci
https://github.com/ral-facilities/inventory-management-system-api/pull/460

update ci env vars for ims api

---

cypress/e2e/with_mock_data/items.cy.ts
src/common/images/__snapshots__/imageGallery.component.test.tsx.snap
src/common/images/galleryLightbox.component.tsx
src/common/images/imageGallery.component.test.tsx

Enter a description of the changes here

Add tooltips to lightbox buttons

---

cypress/e2e/with_mock_data/units.cy.ts
src/admin/units/__snapshots__/units.component.test.tsx.snap
src/admin/units/units.component.test.tsx
src/admin/units/units.component.tsx

Adds the enhanced table filtering to the units table.
Adds new tests for this and updates snapshot.
Resolves #1038

Enhance unit table filtering #1038

---

src/common/attachments/uploadAttachmentsDialog.component.tsx
src/common/images/__snapshots__/imageGallery.component.test.tsx.snap
src/common/images/__snapshots__/primaryImageDialog.component.test.tsx.snap
src/common/images/imageGallery.component.tsx
src/common/images/uploadImagesDialog.component.tsx
src/common/uppy.utils.tsx

https://github.com/ral-facilities/inventory-management-system/pull/1334#issuecomment-2774838571

fix: resolve close button issue in upload attachments dialog

---

src/catalogue/category/catalogueCardView.component.tsx
src/common/images/__snapshots__/imageGallery.component.test.tsx.snap
src/common/images/imageGallery.component.tsx
src/items/__snapshots__/itemsTable.component.test.tsx.snap
src/items/itemsTable.component.tsx
src/systems/__snapshots__/systemItemsTable.component.test.tsx.snap
src/systems/systemItemsTable.component.tsx
src/utils.tsx

- fix created time in the card views 
- stop the tooltips for aggregate cells 

Fix date handling in itemsTable and card views

---

src/common/attachments/__snapshots__/attachmentsTable.component.test.tsx.snap
src/common/attachments/attachmentsTable.component.tsx
src/common/images/__snapshots__/imageGallery.component.test.tsx.snap
src/common/images/__snapshots__/primaryImageDialog.component.test.tsx.snap
src/common/images/imageGallery.component.test.tsx
src/common/images/imageGallery.component.tsx
src/common/images/primaryImageDialog.component.test.tsx
src/common/images/thumbnailImage.component.tsx

- Rename "Upload Image" button to "Upload Images"
- Stop the primary image thumbnail from erroring when the image is not available

Demo Bugfixes

---

cypress/e2e/with_mock_data/items.cy.ts

Adds e2e tests for primary images' features using mock data.

Add mock e2e tests for primary images

---

cypress/e2e/with_mock_data/items.cy.ts
src/common/attachments/uploadAttachmentsDialog.component.test.tsx
src/common/editFileDialog.component.test.tsx
src/common/editFileDialog.component.tsx
src/common/images/uploadImagesDialog.component.test.tsx
src/mocks/handlers.ts
src/utils.tsx

Parse duplicate name error messages for images and attachments
closes #1414

Parse duplicate name error messages for images and attachments #1414

---

.github/workflows/ci-build.yml
cypress/support/commands.ts

Name was changed in https://github.com/ral-facilities/inventory-management-system-api/pull/519 which has now been merged.

Fix CI after change of container name in ims-api

---

package.json
yarn.lock

See Louise's comment here https://github.com/ral-facilities/scigateway/pull/1439#pullrequestreview-2900123241.

Remove @babel/eslint-parser

---

cypress/e2e/with_api/catalogueItems/catalogueItems.cy.ts
src/systems/systemDetails.component.tsx

Fix misaligned subsystem title

---

cypress/e2e/with_mock_data/rules.cy.ts
src/App.tsx
src/admin/__snapshots__/adminCardView.component.test.tsx.snap
src/admin/adminCardView.component.tsx
src/admin/adminLayout.component.tsx
src/admin/rules/__snapshots__/rules.component.test.tsx.snap
src/admin/rules/rules.component.test.tsx
src/admin/rules/rules.component.tsx
src/admin/systemTypes/systemTypes.component.tsx
src/api/api.types.tsx
src/api/rules.test.tsx
src/api/rules.tsx
src/mocks/UsageStatuses.json
src/mocks/handlers.ts
src/mocks/rules.ts
src/paths.tsx
src/testUtils.tsx

View rules #1479

---

cypress/e2e/with_mock_data/catalogueCategories.cy.ts
src/catalogue/category/property/propertyDialog.component.tsx
yarn.lock

see #1513 
update axios to 1.12 see #1512
closes #1513, closes #1512

Add property error (main) #1513
