public/mockServiceWorker.js
src/catalogue/items/catalogueItemsLandingPage.component.test.tsx
src/catalogue/items/catalogueItemsLandingPage.component.tsx
src/manufacturer/manufacturerLandingPage.component.test.tsx
src/manufacturer/manufacturerLandingPage.component.tsx

Add print button on landing page. 
Cypress cannot interact with the browser print dialog. No e2e tests
wait for #144 to add the print button on the manufacturer landing page.
closes #164

Print button on landing pages #164

---

cypress/e2e/catalogue/catalogueCategory.cy.ts
src/catalogue/category/catalogueCategoryDialog.component.test.tsx
src/catalogue/category/catalogueCategoryDialog.component.tsx
src/catalogue/category/cataloguePropertiesForm.component.test.tsx
src/catalogue/category/cataloguePropertiesForm.component.tsx

Implemented logic to prevent duplicate catalogue item property names to be used when creating a catalogue category. Check is not case sensitive so will detect words which are the same (regardless of capitalization). Error messages appear on the properties with duplicate names, and all disappear when an value is changed. Logic works for both adding and editing a catalogue category
closes #181

Duplicate property names fix #181

---

cypress/e2e/catalogue/catalogueCategory.cy.ts
cypress/e2e/catalogue/catalogueItems.cy.ts
cypress/e2e/manufacturer/manufacturer.cy.ts
cypress/e2e/system.cy.ts
src/catalogue/category/catalogueCategoryDialog.component.tsx
src/catalogue/category/cataloguePropertiesForm.component.tsx
src/catalogue/category/deleteCatalogueCategoryDialog.component.tsx
src/catalogue/items/catalogueItemsDialog.component.tsx
src/catalogue/items/deleteCatalogueItemDialog.component.tsx
src/catalogue/items/obsoleteCatalogueItemDialog.component.tsx
src/manufacturer/deleteManufacturerDialog.component.tsx
src/manufacturer/manufacturerDialog.component.tsx
src/systems/deleteSystemDialog.component.tsx
src/systems/systemDialog.component.tsx

Implemented logic so that save/continue buttons in the dialogs are disabled if there is an error in the dialog.
I only refactored the e2e tests that test for errors, to check if the save/continue button is disabled
closes #187

Disable buttons on error #187

---

cypress/e2e/catalogue/catalogueCategory.cy.ts
src/catalogue/catalogue.component.test.tsx
src/catalogue/catalogue.component.tsx
src/catalogue/category/catalogueCard.component.test.tsx
src/catalogue/category/catalogueCard.component.tsx
src/catalogue/category/catalogueCategoryDialog.component.test.tsx
src/catalogue/category/catalogueCategoryDialog.component.tsx

Changed card view to have more actions button which then displays edit, save as and delete options like in catalogue items table view.
Implemented `save as` logic for catalogue categories
closes #172

save-as-for-catalogue-categories-#172

---

cypress/e2e/catalogue/catalogueCategory.cy.ts
cypress/e2e/catalogue/catalogueItems.cy.ts
cypress/e2e/items.cy.ts
cypress/e2e/manufacturer/manufacturer.cy.ts
cypress/e2e/systems.cy.ts
src/manufacturer/manufacturerDialog.component.tsx
src/systems/systems.component.test.tsx

Allows url on its own to be updated in the manufacturer dialog. Also hopefully fixes some flakiness in the e2e tests caused by cypress not waiting for the save button click to finish before asserting the mocked requests so I just added the same fix I applied in #284 everywhere.
Closes #279

Fix manufacturer edit url only #279

---

cypress/e2e/catalogue/catalogueCategory.cy.ts
cypress/e2e/items.cy.ts
cypress/support/commands.ts
src/api/catalogueCategory.tsx
src/api/catalogueItem.tsx
src/api/item.tsx
src/api/manufacturer.tsx
src/api/systems.tsx
src/catalogue/catalogue.component.test.tsx
src/catalogue/catalogue.component.tsx
src/catalogue/category/catalogueCategoryDialog.component.test.tsx
src/catalogue/category/catalogueCategoryDialog.component.tsx
src/catalogue/category/catalogueCategoryDirectoryDialog.component.tsx
src/catalogue/items/catalogueItemDirectoryDialog.component.test.tsx
src/catalogue/items/catalogueItemDirectoryDialog.component.tsx
src/catalogue/items/catalogueItemsDialog.component.test.tsx
src/catalogue/items/catalogueItemsLandingPage.component.tsx
src/catalogue/items/obsoleteCatalogueItemDialog.component.tsx
src/items/deleteItemDialog.component.tsx
src/items/itemDialog.component.test.tsx
src/items/items.component.tsx
src/items/itemsLandingPage.component.tsx
src/mocks/handlers.ts
src/systems/systems.component.tsx

Removes trailing slashes on API urls. They will also be removed on the backend to stop the 307 redirect's that break the production docker version.
Also makes a modification to what we define as the id for a root catalogue category. Previously we had some queries being disabled for `id !== ""` and some for `id !== undefined"`. So I modified all of them to be the same, either "null" or "undefined" to be consistent. This prevents some unnecessary requests from being sent and most importantly one for the `catalogue-items/` in `useCatalogueCategory` when at the root. A change from this also broke some tests that shouldn't really have worked in the first place so I fixed those here too.

Remove trailing slashes on API urls

---

src/catalogue/category/catalogueCategoryDialog.component.tsx
src/catalogue/category/catalogueCategoryDirectoryDialog.component.tsx
src/catalogue/category/deleteCatalogueCategoryDialog.component.tsx
src/catalogue/items/catalogueItemDirectoryDialog.component.tsx
src/catalogue/items/catalogueItemsDialog.component.tsx
src/catalogue/items/deleteCatalogueItemDialog.component.tsx
src/catalogue/items/obsoleteCatalogueItemDialog.component.tsx
src/items/deleteItemDialog.component.tsx
src/items/itemDialog.component.tsx
src/manufacturer/deleteManufacturerDialog.component.tsx
src/manufacturer/manufacturerDialog.component.tsx
src/systems/deleteSystemDialog.component.tsx
src/systems/systemDialog.component.tsx
src/systems/systemDirectoryDialog.component.tsx
src/systems/systemItemsDialog.component.tsx

Implemented `isPending` when requests are made so that buttons then become disabled. This ensures users cannot send multiple requests by continuously clicking on the button
closes #325

Use is pending disable buttons #325

---

src/catalogue/category/cataloguePropertiesForm.component.test.tsx
src/catalogue/category/deleteCatalogueCategoryDialog.component.test.tsx
src/catalogue/items/deleteCatalogueItemDialog.component.test.tsx
src/items/deleteItemDialog.component.test.tsx

Noticed a warning in https://github.com/ral-facilities/inventory-management-system/actions/runs/8249904474/job/22563345507, caused by not having an await on a user.click, so found all that were missing and added them in here.

Add missing awaits for user.click in unit tests

---

vite.config.ts

Type hinting doesn't appear to work properly in vscode when splitting up the config like this, so I only noticed it while migrating SciGateway. As it was a non-empty string it would still have been evaluated to true so shouldn't have had any effect.

Fix incorrect type in vite config

---

src/catalogue/catalogue.component.tsx
src/systems/systems.component.tsx

stops the catalogue category query from setting the id to empty string. Changes this default to "null" (i.e. "null")
fix error when catalogue category data is undefined 
closes #402

stop-CC-query-at-/-#402

---

src/catalogue/items/catalogueItemDirectoryDialog.component.tsx
src/systems/systemItemsDialog.component.tsx

Fixed bug where adding a system/catalogue category in a directory dialog adds them to the root instead of as a child of the system/catalogue category
closes #403

fixed bugs in systems and catalogue items directory dialogs #403

---

src/catalogue/items/CatalogueItemsDetailsPanel.component.test.tsx
src/catalogue/items/CatalogueItemsDetailsPanel.component.tsx
src/catalogue/items/__snapshots__/CatalogueItemsDetailsPanel.component.test.tsx.snap
src/items/ItemsDetailsPanel.component.test.tsx
src/items/ItemsDetailsPanel.component.tsx
src/items/__snapshots__/ItemsDetailsPanel.component.test.tsx.snap
src/systems/__snapshots__/systemItemsTable.component.test.tsx.snap
src/systems/systemItemsTable.component.tsx

Adds column spacing to properties on catalogue item & item details panels. Ideally we would use 100% width on the grid container so the grid could use `space-between` or something but unfortunately MRT renders MUI collapse elements above with a width that can't be modified, and using the example given on MRT fails when columnResizing is `true` currently.
This PR also removes some unnecessary Grid's and moves Notes from the `Details` tab to a separate `Notes` tab on catalogue item details panels to match the items one.
Closes #394

Fix spacing items details panels #394

---

src/systems/systems.component.tsx

Tweaks subsystems that can be displayed to 15, 30 and 45 like the items in the tables on the systems page.

Tweak subsystems per page

---

.github/workflows/ci-build.yml
Dockerfile
Dockerfile.prod

This PR pins the base docker images in the Dockerfiles to commit SHAs so that Renovate (or Dependabot if Renovate doesn't work) can create PRs each time there is a change in the upstream base images that the base images are set to use as new SHAs are generated on every upstream change. Not sure if Renovate will also update the OS versions but if it doesn't then we will have to do the Alpine version updates manually for now.
Please note that I have pinned it to an older SHA to verify that Renovate (or Dependabot if Renovate doesn't work) will create a PR.

Pin docker images to SHA

---

src/api/api.tsx
src/handleIMS_APIError.test.ts
src/handleIMS_APIError.ts

Resolves requests immediately if the user is not logged in and is trying to access a protected resource, rather than before which attempted to refresh the token. Also hides the error message when this occurs (as well as any 403 as it is assumed this should be handled by SciGateway like in DataGateway).
I also noticed that the status check was wrong, meaning the error message for a 500 error would not be used so I fixed that here.
Closes #399

Resolve authenticated request immediately if not logged in #399

---

vite.config.ts

Should fix vscode extensions not picking up coverage. I tried this with https://marketplace.visualstudio.com/items?itemName=markis.code-coverage.
Should make the same change to the vite branch of SciGateway if this works.
Closes #473

Modify vite config to output an lcov.info #473

---

src/systems/__snapshots__/systemItemsTable.component.test.tsx.snap
src/systems/systemItemsTable.component.tsx

Fixed bug in moveTo dialog for items in systems where row totals were returning undefined
closes #569

fixed moveTo total row bug in systemItems table #569

---

src/catalogue/items/__snapshots__/catalogueItemsTable.component.test.tsx.snap
src/catalogue/items/catalogueItemsTable.component.test.tsx
src/catalogue/items/catalogueItemsTable.component.tsx

See #585. Added two short unit tests to cover in the future although as part of that I noticed that we don't seem to need the `waitFor`'s on the move to and copy to buttons. Just as well as if we did these two new tests wouldn't make sense. (Have checked for missing act warning and haven't seen any test flakiness myself)
Closes #585

Hide move & copy to buttons on obsolete catalogue item dialogue #585

---

Dockerfile
Dockerfile.prod

Bumps `node` from `20.14.0-alpine3.19` to `20.14.0-alpine3.20` and `httpd` from `2.4.58-alpine3.19` to `2.4.59-alpine3.20`.

Bump Docker base images

---

src/catalogue/catalogue.component.tsx

See #617. This was caused by not waiting on all the data to be loaded as the catalogue categories data wouldn't start loading until after the parent has already been loaded.
Closes #617

Fix no loading indicator for CC no results #617

---

renovate.json

See #755. I hope this config enable updates on `main` and `v*` but only for dockerfiles or github-actions. Also removed cdnurl as it was from OG.
Can't really validate what it will do until merged. It passed `npx --yes --package renovate -- renovate-config-validator`. It is also  possible to run locally using `LOG_LEVEL=debug npx renovate --platform=local --repository-cache=reset > output.txt` but it doesn't take into account the branches (see https://docs.renovatebot.com/modules/platform/local/) so the best I could do is test it while deleting the branch matching to ensure it either detected an update or not based on the rest of the config.
Closes #755

Configure Renovate to update release branches

---

cypress/e2e/with_api/items/functions.ts
cypress/e2e/with_mock_data/items.cy.ts
src/form.schemas.tsx
src/items/itemDialog.component.test.tsx
src/items/itemDialog.component.tsx

Prevent an item's delivered date being set to a date in the future.
By setting maxDate as DATE_TODAY instead of DATE_PICKER_MAX_DATE.
Also fixes an incorrect comment (see #1052)
Resolves #1014 
Resolves #1052

Prevent an item's delivered date being set in the future #1014

---

yarn.lock

~~I intended to only add the resolution to force the update. But it ended up requiring it as if I remove it, the next yarn install immediately replaces rollup with the latest version which hasn't even made 24 hours after release yet. So had to leave it in.~~
~~(We should probably remove it on develop once merged)~~
Updated using `yarn set resolution rollup@npm:^4.20.0 npm:4.22.5`.

Update rollup to v4.22.5

---

cypress/e2e/with_mock_data/catalogueItems.cy.ts
src/catalogue/items/catalogueItemsDialog.component.test.tsx
src/form.schemas.tsx

To provide negative number validation, set min:0 for cost and days variables.
Adds a unit test, and additional testing to cypress e2e with mock data test.
Resolves #970

Prevent negative numbers being set where they shouldn't be in Catalogue Items #970

---

cypress/e2e/with_mock_data/catalogueItems.cy.ts
src/catalogue/items/catalogueItemsDialog.component.test.tsx
src/form.schemas.tsx

Add negative number validation for expected lifetime field in catalogue items dialog.

Add negative number validation to Expected Lifetime

---

src/catalogue/items/catalogueItemsTable.component.tsx
src/manufacturer/__snapshots__/manufacturer.component.test.tsx.snap
src/manufacturer/manufacturer.component.tsx

- remove optional filter in manufacturer address in catalogue items table
closes #1037

Enhance manufacturers table filtering #1037

---

vite.config.ts

From comment on https://github.com/ral-facilities/scigateway/pull/1380.

Remove unnecessary open config to match SciGateway

---

src/common/preservedTableState.component.test.tsx
src/common/preservedTableState.component.tsx

See #1146. Manually resets the page index for operations that are expected to change the length of the filtered results.
This is branched off main. Will need merging into develop afterwards.
Closes #1146

Fix filtering and similar being on empty page when there are results #1146

---

src/catalogue/category/catalogueCardView.component.test.tsx
src/catalogue/category/catalogueCardView.component.tsx
src/items/itemsTable.component.test.tsx
src/items/itemsTable.component.tsx
src/utils.test.tsx
src/utils.tsx

Enhance catalogue category card filters #1124

---

src/common/images/uploadImagesDialog.component.tsx

Remove limit for parallel images upload. This has been fix in the object store api

Remove limit for parallel images upload

---

.dockerignore
.yarn/patches/@uppy-aws-s3-npm-4.1.3-4c4ba3e640.patch
package.json
yarn.lock

Set the ETag value to empty string and remove the warnings. This had to be doe in the index.js for it to work (not the tsx in the src).  
This can be tested by using the mock data. To do this you would need to remove the ETag from post response(''/object-storage'')
closes #1292

Patch Uppy AwsS3 to not expect the ETag #1292

---

Dockerfile.prod

The space around the equal is not the correct syntax and causes in when just to build for the full ims docker stack

Remove spacing around the equals for OS_API_URL #1288

---

src/catalogue/items/__snapshots__/catalogueItemsDetailsPanel.component.test.tsx.snap
src/catalogue/items/catalogueItemsDetailsPanel.component.test.tsx
src/catalogue/items/catalogueItemsDetailsPanel.component.tsx
src/catalogue/items/catalogueItemsLandingPage.component.test.tsx
src/catalogue/items/catalogueItemsLandingPage.component.tsx
src/items/__snapshots__/itemsDetailsPanel.component.test.tsx.snap
src/items/itemsDetailsPanel.component.test.tsx
src/items/itemsDetailsPanel.component.tsx
src/items/itemsLandingPage.component.test.tsx
src/items/itemsLandingPage.component.tsx
src/systems/__snapshots__/systemItemsTable.component.test.tsx.snap
src/systems/systemItemsTable.component.tsx

see #1278 #1280
closes #1278, closes #1280

Fix: Grouping by Id instead of name and include expected Lifetime days in the table #1278

---

.github/workflows/ci-build.yml
Dockerfile
Dockerfile.prod

Updates node to 20.18.3-alpine3.21 and httpd to 2.4.63-alpine3.21 in docker images. Ignoring node 20.19 as its an hour old.

Update node to 20.18.3-alpine3.21 and httpd to 2.4.63-alpine3.21 in docker images

---

package.json
yarn.lock

Bump @babel/runtime from 7.24.8 to 7.26.10 and @babel/helpers from 7.24.8 to 7.26.10. Cherry picked from develop (although changes still had to effectively be done manually as the versions have already changed on develop so didn't apply correctly.
This change matches one done to SciGateway to two security vulnerabilities that only appeared today.
Will release a patch version v1.0.6 once merged.

Bump @babel/runtime from 7.24.8 to 7.26.10 and @babel/helpers from 7.24.8 to 7.26.10

---

cypress/e2e/with_mock_data/items.cy.ts
src/common/attachments/__snapshots__/attachmentsTable.component.test.tsx.snap
src/common/attachments/attachmentsTable.component.test.tsx
src/common/attachments/attachmentsTable.component.tsx
src/manufacturer/manufacturerTable.component.test.tsx

- Add upload attachment button into attachments table, and add unit test for it
- Add cypress test for opening and closing upload attachments dialog - tests the dialog can be opened and closed when accessed via both the actions menu and the table button
Resolves #1308

Add upload attachment button to attachments table #1308

---

README.md

Found a reminder to do this in a document I made at the start of the rotation 😆

Fix incorrect local setup instruction in README

---

.github/workflows/ci-build.yml

Replicates Viktor's changes from scigateway-auth and object-storage-api to prevent us from pushing images each time the CI runs, and instead only when manually requested.
It appears `workflow_dispatch` was not in the CI action before now, unlike on the backend, so I cannot execute this as a test, it has to be merged to allow you to manually run it instead. However see the similar run here https://github.com/ral-facilities/inventory-management-system-api/actions/runs/14401560315/job/40388375982.
E.g.
https://github.com/ral-facilities/inventory-management-system-api/actions/workflows/.ci.yml
Closes #1326

Only push docker images when manually requested #1326

---

src/common/attachments/uploadAttachmentsDialog.component.tsx

Ensure that removing a file from the upload dialog does not unintentionally delete successfully upload images. This resolves issues with accidental image loss during file upload.
Do not broadcast the delete error as this is a silent error 
https://github.com/user-attachments/assets/69065f1e-3ea8-4e84-a336-04063a0f701b

fix: prevent image deletion when file is removed from upload dialog

---

package.json
yarn.lock

Instead of https://github.com/ral-facilities/inventory-management-system/pull/1396. I double checked and this package is no longer needed as the types come with `@eslint/js` now anyway. It might have been left by accident, SciGateway and OG don't have it either.

Remove @types/eslint__js as no longer needed

---

eslint.config.js
package.json
yarn.lock

Found while doing https://github.com/ral-facilities/scigateway/pull/1439. eslint-plugin-react-hooks now supports the flat config.

Remove @eslint/compat as no longer required for react-hooks

---

Dockerfile.prod
package.json

OG and DG now use defaults for the browserslist config, so I updated the SciGateway branch to do the same, and replicating here. Also noticed this warning
on https://github.com/ral-facilities/ldap-jwt-auth/pull/227/files so fixed here too.

Update browserslist config to match DG & OG and fix FromAsCasing in dockerfile

---

src/admin/units/__snapshots__/units.component.test.tsx.snap
src/admin/units/units.component.tsx
src/admin/usageStatuses/__snapshots__/usageStatuses.component.test.tsx.snap
src/admin/usageStatuses/usageStatuses.component.tsx
src/catalogue/category/property/propertyDialog.component.tsx
src/catalogue/items/catalogueItemsDialog.component.tsx
src/items/itemDialog.component.tsx

Fixes scrollbars mentioned in #1449, was similar to https://github.com/ral-facilities/inventory-management-system/pull/1445, we were both fixing the height and allowing it to expand.
Fixes deleting the value of an allowed value property in the catalogue item/item dialogue previously displaying null #1447. This should be tested with string and number values as both were effected.
Fixes deleting the default value in property dialogue displays undefined #1446. Still not convinced on the reasoning for this happening but I have implemented a fix for it. Test with both integer and string values of the default value.
Fixes a scrollbar appearing when using the advanced section of the items dialogue and specifying a start index.
Add a set up instructions describing how the reviewer should test the …

Some bug fixes for v2 #1449

---

src/catalogue/category/catalogueCardView.component.tsx
src/catalogue/category/deleteCatalogueCategoryDialog.component.test.tsx
src/catalogue/category/deleteCatalogueCategoryDialog.component.tsx
src/catalogue/items/catalogueItemsTable.component.tsx
src/catalogue/items/deleteCatalogueItemDialog.component.test.tsx
src/catalogue/items/deleteCatalogueItemDialog.component.tsx
src/utils.tsx

bugfix: Catalogue category selection persists when navigating #1452

---

cypress/e2e/with_api/catalogueCategories/functions.ts
cypress/e2e/with_api/catalogueItems/catalogueItems.cy.ts
cypress/e2e/with_api/catalogueItems/functions.ts
cypress/e2e/with_api/systems/functions.ts

This PR Covers most of the changes lost due to the cloud outage, and a few extra test fixes (the 2 `.click({force: true})` were new additions).
The WSL VM was far less flaky than the  VM when running tests, meaning there is a chance that there will still be test failures when testing on the cloud VMs. The only error that did not occur (from my memory, there may have been more failures on the cloud PR), was the following:
- On navigating to the home, the test may interact with elements before loading is complete. To fix this I added an assertion to check for the absence of a breadcrumb, using it's datatest-id as a reference to find it. The assertion was something like `cy.findByTestId('my-element').should('not.exist')` or `cy.get('[data-testid="my-element"]').should('not.exist')`
A vast …

Recover Lost VM changes (e2e api)
